# Generated by Django 3.1.6 on 2021-06-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbeneficiary',
            name='sincome',
            field=models.IntegerField(default=''),
        ),
    ]
