# Generated by Django 3.1.6 on 2021-06-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statusdb',
            new_name='Statusdbs',
        ),
    ]
