# Generated by Django 3.1.6 on 2021-04-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0002_item_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
    ]
