# Generated by Django 3.1.6 on 2021-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0002_auto_20210627_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbeneficiary',
            name='bresidents',
        ),
        migrations.AddField(
            model_name='sbeneficiary',
            name='bresidents',
            field=models.ManyToManyField(default=None, to='MNList.BResidents'),
        ),
        migrations.AlterField(
            model_name='statusdbs',
            name='ddate',
            field=models.DateTimeField(default=''),
        ),
    ]
