# Generated by Django 3.1.6 on 2021-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0002_auto_20210616_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdb',
            name='sbeneficiary',
        ),
        migrations.AddField(
            model_name='statusdb',
            name='sdistributions',
            field=models.ManyToManyField(default=None, to='MNList.SDistributions'),
        ),
    ]
