# Generated by Django 3.1.6 on 2021-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0003_auto_20210622_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdb',
            name='sdistributions',
        ),
        migrations.AddField(
            model_name='statusdb',
            name='sbeneficiary',
            field=models.ManyToManyField(default=None, to='MNList.SBeneficiary'),
        ),
    ]
