# Generated by Django 3.1.6 on 2021-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0004_auto_20210622_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdistributions',
            name='dddate',
        ),
        migrations.RemoveField(
            model_name='sdistributions',
            name='dlocation',
        ),
        migrations.RemoveField(
            model_name='sdistributions',
            name='sbeneficiary',
        ),
        migrations.AddField(
            model_name='statusdb',
            name='sdistribution',
            field=models.ManyToManyField(default=None, to='MNList.SDistributions'),
        ),
    ]
