# Generated by Django 3.1.6 on 2021-06-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0005_auto_20210623_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdistributions',
            name='dbank',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sdistributions',
            name='ddigital',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sdistributions',
            name='dothers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statusdb',
            name='ddate',
            field=models.DateField(default=''),
        ),
    ]
