# Generated by Django 3.1.6 on 2021-06-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0006_auto_20210624_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdistributions',
            name='dbank',
        ),
        migrations.RemoveField(
            model_name='sdistributions',
            name='ddigital',
        ),
        migrations.RemoveField(
            model_name='sdistributions',
            name='dothers',
        ),
    ]
