# Generated by Django 3.1.6 on 2021-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0007_auto_20210624_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdistributions',
            name='dbank',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sdistributions',
            name='ddigi',
            field=models.TextField(default=''),
        ),
    ]
