# Generated by Django 3.1.6 on 2021-04-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0007_auto_20210425_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='textAdd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='textFM',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='textRS',
            field=models.TextField(default=''),
        ),
    ]
