# Generated by Django 3.1.6 on 2021-06-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0008_auto_20210624_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmode', models.TextField(default='')),
                ('dplace', models.TextField(default='')),
                ('dlocation', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='statusdb',
            name='sdistribution',
        ),
        migrations.AddField(
            model_name='sbeneficiary',
            name='dtranche',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='SDistributions',
        ),
        migrations.AddField(
            model_name='slocation',
            name='sbeneficiary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.sbeneficiary'),
        ),
    ]
