# Generated by Django 3.1.6 on 2021-04-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0008_auto_20210428_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text2',
            field=models.TextField(default=''),
        ),
    ]
