# Generated by Django 3.1.6 on 2021-06-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0010_auto_20210624_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SLocation',
            new_name='SDistributions',
        ),
        migrations.RenameField(
            model_name='sbeneficiary',
            old_name='dtranche',
            new_name='stranche',
        ),
        migrations.AddField(
            model_name='statusdb',
            name='sdistribution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.sdistributions'),
        ),
    ]
