# Generated by Django 3.1.6 on 2021-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0012_remove_sdistributions_sbeneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdb',
            name='sdistribution',
        ),
        migrations.AddField(
            model_name='statusdb',
            name='sdistribution',
            field=models.ManyToManyField(default=None, to='MNList.SDistributions'),
        ),
    ]
