# Generated by Django 3.1.6 on 2021-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0012_auto_20210428_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textFM', models.TextField(default='')),
                ('textRS', models.TextField(default='')),
                ('textAdd', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='textAdd',
        ),
        migrations.RemoveField(
            model_name='item',
            name='textFM',
        ),
        migrations.RemoveField(
            model_name='item',
            name='textRS',
        ),
    ]
