# Generated by Django 3.1.6 on 2021-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0013_auto_20210428_0520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAPinfo',
        ),
        migrations.AddField(
            model_name='item',
            name='textAdd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='textFM',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='textRS',
            field=models.TextField(default=''),
        ),
    ]
