# Generated by Django 3.1.6 on 2021-04-29 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0014_auto_20210428_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='IInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('textID', models.TextField(default='')),
                ('textFM', models.TextField(default='')),
                ('textRS', models.TextField(default='')),
                ('textAdd', models.TextField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='IBrgy',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='iinfo',
            name='brgy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='MNList.ibrgy'),
        ),
    ]
