# Generated by Django 3.1.6 on 2021-04-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0016_auto_20210429_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='brgy',
            new_name='ibrgy',
        ),
    ]
