# Generated by Django 3.1.6 on 2021-05-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0020_auto_20210515_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibrgy',
            name='text',
        ),
        migrations.RemoveField(
            model_name='ibrgy',
            name='textID',
        ),
        migrations.AddField(
            model_name='info',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='textID',
            field=models.TextField(default=''),
        ),
    ]
