# Generated by Django 3.1.6 on 2021-05-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0024_auto_20210516_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ibrgy',
            old_name='bbrgy',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='ibrgy',
            old_name='bbrgyID',
            new_name='textID',
        ),
        migrations.RemoveField(
            model_name='info',
            name='text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='textID',
        ),
    ]
