# Generated by Django 3.1.6 on 2021-05-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0026_auto_20210516_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='text',
        ),
        migrations.RemoveField(
            model_name='info',
            name='textID',
        ),
        migrations.AddField(
            model_name='ibrgy',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ibrgy',
            name='textID',
            field=models.TextField(default=''),
        ),
    ]
