# Generated by Django 3.1.6 on 2021-05-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0027_auto_20210516_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ibrgy',
            old_name='text',
            new_name='bID',
        ),
        migrations.RenameField(
            model_name='ibrgy',
            old_name='textID',
            new_name='bname',
        ),
    ]
