# Generated by Django 3.1.6 on 2021-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0028_auto_20210516_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibrgy',
            name='mncplty',
            field=models.TextField(default=''),
        ),
    ]
