# Generated by Django 3.1.6 on 2021-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0029_ibrgy_mncplty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BResidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.TextField(default='')),
                ('rrelation', models.TextField(default='')),
                ('radd', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SBeneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scategory', models.TextField(default='')),
                ('samount', models.TextField(default='')),
                ('bresidents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.bresidents')),
            ],
        ),
        migrations.CreateModel(
            name='SDistributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmode', models.TextField(default='')),
                ('ddate', models.DateTimeField(default='')),
                ('sbeneficiary', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.sbeneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstatus', models.TextField(default='')),
                ('ddate', models.DateTimeField(default='')),
                ('sdistributions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.sdistributions')),
            ],
        ),
        migrations.AlterField(
            model_name='ibrgy',
            name='bID',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AddField(
            model_name='bresidents',
            name='ibrgy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.ibrgy'),
        ),
    ]
