# Generated by Django 3.1.6 on 2021-05-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0030_auto_20210517_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbeneficiary',
            old_name='bresidents',
            new_name='info',
        ),
    ]
