# Generated by Django 3.1.6 on 2021-05-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0031_auto_20210517_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbeneficiary',
            old_name='info',
            new_name='bresidents',
        ),
    ]
