# Generated by Django 3.1.6 on 2021-05-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0032_auto_20210517_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdistributions',
            name='ddate',
        ),
        migrations.AddField(
            model_name='sdistributions',
            name='dlocation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sdistributions',
            name='dtranche',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statusdb',
            name='dremarks',
            field=models.TextField(default=''),
        ),
    ]
