# Generated by Django 3.1.6 on 2021-06-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0033_auto_20210518_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bresidents',
            old_name='rname',
            new_name='rfname',
        ),
        migrations.RenameField(
            model_name='bresidents',
            old_name='rrelation',
            new_name='rjob',
        ),
        migrations.RenameField(
            model_name='sbeneficiary',
            old_name='scategory',
            new_name='sclass',
        ),
        migrations.AddField(
            model_name='bresidents',
            name='rlname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bresidents',
            name='rmname',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='RDependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlname', models.TextField(default='')),
                ('dfname', models.TextField(default='')),
                ('dmname', models.TextField(default='')),
                ('drelation', models.TextField(default='')),
                ('djob', models.TextField(default='')),
                ('bresidents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MNList.bresidents')),
            ],
        ),
    ]
