# Generated by Django 3.1.6 on 2021-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0034_auto_20210613_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bresidents',
            name='rnumber',
            field=models.TextField(default=''),
        ),
    ]
