# Generated by Django 3.1.6 on 2021-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0035_bresidents_rnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bresidents',
            name='rnumber',
            field=models.IntegerField(default=''),
        ),
    ]
