# Generated by Django 3.1.6 on 2021-06-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0036_auto_20210613_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdistributions',
            name='dplace',
            field=models.TextField(default=''),
        ),
    ]
