# Generated by Django 3.1.6 on 2021-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0038_auto_20210614_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bresidents',
            name='drelation',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='RDependent',
        ),
    ]
