# Generated by Django 3.1.6 on 2021-06-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0039_auto_20210614_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bresidents',
            old_name='drelation',
            new_name='rrelation',
        ),
    ]
