# Generated by Django 3.1.6 on 2021-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0040_auto_20210614_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbeneficiary',
            name='scategory',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sbeneficiary',
            name='sincome',
            field=models.TextField(default=''),
        ),
    ]
