# Generated by Django 3.1.6 on 2021-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0041_auto_20210614_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdb',
            name='dperson',
            field=models.TextField(default=''),
        ),
    ]
