# Generated by Django 3.1.6 on 2021-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MNList', '0042_statusdb_dperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdistributions',
            name='dddate',
            field=models.DateTimeField(default=''),
        ),
    ]
